---
title: "Construct Full Data"
author: "Ellie Cox"
date: "2022-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages

```{r loadpackages}
library(dplyr)
library(foreign)
```

## Read Data

```{r loaddata}
load("/Users/elizabeth/Documents/Capstone Paper/RightHandSide.Rdata") # created in a previous file
controls <- read.csv("/Users/elizabeth/Documents/Capstone Paper/usa_00009.csv")
```

## Construct controls

```{r cleanupvariables}
## Make fips 
controls$STATEFIP <- paste(formatC(controls$STATEFIP, width=2, flag="0"))
controls$COUNTYFIP <- paste(formatC(controls$COUNTYFIP, width=3, flag="0"))
controls$FIPS <- paste0(controls$STATEFIP, controls$COUNTYFIP)

## Race controls - logic taken from econometrics PA 2
controls$hispanic <- rep(0, length(controls$YEAR))
controls$hispanic[which(controls$HISPAND != 0 & controls$HISPAND != 900)] <- 1
controls$black <- rep(0, length(controls$YEAR))
controls$black[which(controls$RACED == 200 & controls$hispanic ==0)] <- 1
controls$asian <- rep(0, length(controls$YEAR))
controls$asian[which(controls$RACED >= 400 & controls$RACED <= 699 & controls$hispanic == 0)] <- 1
controls$native <- rep(0, length(controls$YEAR))
controls$native[which(controls$RACED >= 300 & controls$RACED <= 399 & controls$hispanic == 0)] <- 1
controls$white <- rep(0, length(controls$YEAR))
controls$white[which(controls$RACED == 100 & controls$hispanic == 0)] <- 1
controls$othrace <- rep(0, length(controls$YEAR))
controls$othrace[which(controls$hispanic == 0 & controls$black == 0 & controls$asian == 0 & controls$native==0 & controls$white == 0)] <- 1
check = sum(controls$hispanic, controls$black, controls$asian, controls$native, controls$white, controls$othrave)
table(check)

controls$race_cat5 <- rep(5, length(controls$YEAR))
controls$race_cat5[which(controls$RACED == 1 & controls$hispanic == 0)] <- 1
controls$race_cat5[which(controls$RACED == 200 & controls$hispanic == 0)] <- 2
controls$race_cat5[which(controls$RACED >= 400 & controls$RACED <= 699 & controls$hispanic == 0)] <- 3
controls$race_cat5[which(controls$HISPAND != 0 & controls$HISPAND != 900)] <- 4

# sex
controls$female <- rep(0, length(controls$YEAR))
controls$female[which(controls$SEX == 2)] <- 1
controls$male <- rep(0, length(controls$YEAR))
controls$male[which(controls$SEX == 1)] <- 1

# schooling
controls$schoolyr = rep(0, length(controls$YEAR))
controls$schoolyr[which(controls$EDUCD <= 17)] <- 2.5
controls$schoolyr[which(controls$EDUCD >= 20 & controls$EDUCD <= 23)] <- 5.5
controls$schoolyr[which(controls$EDUCD >= 24 & controls$EDUCD <= 26)] <- 7.5
controls$schoolyr[which(controls$EDUCD == 30)] <- 9
controls$schoolyr[which(controls$EDUCD == 40)] <- 10
controls$schoolyr[which(controls$EDUCD == 50)] <- 11
controls$schoolyr[which(controls$EDUCD >= 60 & controls$EDUCD <= 64)] <- 12
controls$schoolyr[which(controls$EDUCD >= 65 & controls$EDUCD <= 71)] <- 13
controls$schoolyr[which(controls$EDUCD >=80 & controls$EDUCD <= 90)] <- 14
controls$schoolyr[which(controls$EDUCD >= 100 & controls$EDUCD <= 101)] <- 16
controls$schoolyr[which(controls$EDUCD >= 110 & controls$EDUCD <= 115)] <- 18
controls$schoolyr[which(controls$EDUCD == 116)] <- 20

# Employment
controls$nolabforce <- rep(0, length(controls$YEAR))
controls$nolabforce[which(controls$LABFORCE == 1)] <- 1
controls$inlabforce <- rep(0, length(controls$YEAR))
controls$inlabforce[which(controls$LABFORCE == 2)] <- 1
controls$employed <- rep(0, length(controls$YEAR))
controls$employed[which(controls$EMPSTAT == 1)] <- 1
controls$unemployed <- rep(0, length(controls$YEAR))
controls$unemployed[which(controls$EMPSTAT == 2)] <- 1

## Intervalled weeks worked - also taken from econometrics PA
intervalled_weeksworked <- rep(0, length(controls$YEAR))
intervalled_weeksworked[which(controls$WKSWORK2 == 1)] <- 7
intervalled_weeksworked[which(controls$WKSWORK2 == 2)] <- 20
intervalled_weeksworked[which(controls$WKSWORK2 == 3)] <- 33
intervalled_weeksworked[which(controls$WKSWORK2 == 4)] <- 43.5
intervalled_weeksworked[which(controls$WKSWORK2 == 5)] <- 48.5
intervalled_weeksworked[which(controls$WKSWORK2 == 6)] <- 51

## Intervalled usual hours worked 
intervalled_hrsworked <- rep(0, length(controls$YEAR))
intervalled_hrsworked[which(controls$HRSWORK2 == 1)] <- 7
intervalled_hrsworked[which(controls$HRSWORK2 == 2)] <- 22
intervalled_hrsworked[which(controls$HRSWORK2 == 3)] <- 32
intervalled_hrsworked[which(controls$HRSWORK2 == 4)] <- 37
intervalled_hrsworked[which(controls$HRSWORK2 == 5)] <- 40
intervalled_hrsworked[which(controls$HRSWORK2 == 6)] <- 44.5
intervalled_hrsworked[which(controls$HRSWORK2 == 7)] <- 54
intervalled_hrsworked[which(controls$HRSWORK2 == 8)] <- 60

#hrs - intervalled
controls$hrs <- controls$UHRSWORK

## Filter fishy data
controls <- controls %>% 
  filter(hrs < 99)

```

```{r summarise}
controls_county_year <- controls %>% filter(employed == 1) %>%
  group_by(YEAR, FIPS) %>% 
  summarise(hrs = mean(hrs), 
            age = mean(AGE), 
            perwt = sum(PERWT),
            female = sum(female),
            male = sum(male),
            schoolyr = mean(schoolyr),
            hispanic = sum(hispanic),
            black = sum(black),
            asian = sum(asian),
            native = sum(native),
            white = sum(white),
            othrace = sum(othrace),
            inlaborforce = sum(inlabforce), # this is the labor force participation rate. ie. #in labor force/population
            employed = sum(employed),
            unemployed = sum(unemployed),
            income = mean(INCTOT))
```

## Merge to create final dataframe

```{r merge}
## filter to years I need
Data_out$YEAR <- as.character(Data_out$year)
Data_out_filtered <- Data_out %>% filter(YEAR == 1980 | YEAR == 1990 | YEAR == 2000 | YEAR == 2005)
controls_county_year$YEAR <- as.character(controls_county_year$YEAR)

## Merge with Data_out

Data_with_Labor <- left_join(controls_county_year, Data_out_filtered, by.x = c("FIPS", "YEAR"), by.y = c("FIPS", "YEAR"))

#drop non matching rows that produced NA (there's only about 300)
Data_with_Labor <- Data_with_Labor[!(is.na(Data_with_Labor$DownstreamOfHighViolatingCounty)),]
Data_with_Labor <- Data_with_Labor[!(is.na(Data_with_Labor$NumViolators_NumFacilities)),]

## Add intensity in 1985 variable and downstream (only varies at county level)
Intensity_1985 <- Data_out %>% filter(YEAR == "1985") 
Intensity_of_treatment <- as.data.frame(cbind(Intensity_1985$NumViolators_NumFacilities,
                                              Intensity_1985$DownstreamOfHighViolatingCounty,
                                        Intensity_1985$FIPS))
colnames(Intensity_of_treatment)[1] <- "Treatment_Intensity"
colnames(Intensity_of_treatment)[2] <- "Downstream"
colnames(Intensity_of_treatment)[3] <- "FIPS"     

## Merge intensity of treatment with Data_with_Labor
Data_with_Labor <- left_join(Data_with_Labor, Intensity_of_treatment, by.x = "FIPS",
                             by.y = "FIPS")
```



## Write to .dta

```{r writedta}
write.dta(data = as.data.frame(Data_with_Labor), file = "/Users/elizabeth/Documents/Capstone Paper/DiD_Data_Employed.dta")
```

## Write to .Rdata

```{r writeRdata}
save(Data_with_Labor, file = "/Users/elizabeth/Documents/Capstone Paper/DiDData_Employed.Rdata")
```

## Write to .Rdata

```{r writeRdata}
save(data_robust, file = "/Users/elizabeth/Documents/Capstone Paper/RobustData.Rdata")
```



